### ISSUE TITLE
Grouping 0% rows in stats to one row so table uses less space

### ISSUE THREAD

**Issue by ariarzer** [browserslist/browsersl.ist#338]
<img width="578" alt="image" src="https://user-images.githubusercontent.com/27442574/183876907-7d8a46b2-73a1-4603-94a5-5a7025d04b8b.png">

**Comment by ai** [comment]
Close since @a-chabin found that it is not very useful for many cases

**Comment by a-chabin** [comment]
Cases (for history):
1. Groups bad for queries with `last N versions`. We expect N items
2. Let `>0%` or `since 2012`  shows that the bundle size will be large
3. Writing with `-` character is already used in the ranges of minor versions. Designers have not yet come up with a simple and successful solution for grouping elements in a table.
